---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo2
  namespace: default
spec:
  selector:
    matchLabels:
      app: podinfo2
  template:
    metadata:
      labels:
        app: podinfo2
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:5.0.3 # {"$imagepolicy": "flux-system:podinfo2"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP

"This REALLY shouldn't trigger a pull request"
