---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: fluxcdbot/podinfo
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./clusters/my-cluster
    strategy: Setters

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: podinfo2
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        Bump {{range .Updated.Images.}}{{println .Identifier}}{{end}} version

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
          - {{ $filename }}
        {{ end -}}
        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
          - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}
        Images:
        {{ range .Updated.Images -}}
          - {{.}}
        {{ end -}}
        Automation name: {{ .AutomationObject }}
    push:
      branch: fluxcdbot/podinfo2
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./clusters/my-cluster/podinfo2
    strategy: Setters
