---
name: Flux Image Update Auto-PR

on:  # yamllint disable-line rule:truthy
  create:
    branches:
      - fluxcdbot/**

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: pull-request
        run: |
          gh pr create --base "main" --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
