---
name: Flux Image Update Auto-PR

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  create:
    branches:
      - fluxcdbot/**

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: checkout
        with:
          fetch-depth: 50

      - name: pull-request
        run: |
          gh pr create --base "main" --title "" --body ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
