---
name: Flux Image Update Auto-PR

on:  create

permissions:
  pull-requests: write

jobs:
  pull-request:
    if: ${{ startsWith(github.head_ref, 'fluxcdbot/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: checkout
        with:
          fetch-depth: 0

      - name: pull-request
        run: |
          gh pr create --base "main" --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
